apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mpm-storage-class
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2 # AWS EBS storage class (https://aws.amazon.com/ebs/general-purpose/)