apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps/mpm-backend.yaml
  - configmaps/mpm-frontend.yaml
  - deployments/mpm-backend.yaml
  - deployments/mpm-frontend.yaml
  - deployments/mpm-scheduler.yaml
  - deployments/redis.yaml
  - services/mpm-backend.yaml
  - services/mpm-frontend.yaml
